In [1]:
import numpy as np

## Gram-Schmidt Procedure

A method for turning a linearly independent list into an orthonormal list with the same span as the original list

**Orthonormal Basis** - A list of vectors is called _orthonormal_ if each vector in the list has norm 1 _and_ is orthogonal to all the other vectors in the list

 - Column vectors must have a norm = 1
 - Show that the dot product between any two of them is = 0

Given three vectors $u, v, w$

In [4]:
u = np.array([1, 2, 0])
v = np.array([8, 1, -6])
w = np.array([0, 0, 1])

A = np.array([u, v, w]).T

print(A)
print('\n')
print(np.linalg.det(A)) ## indeed, the list of vectors is independent

[[ 1  8  0]
 [ 2  1  0]
 [ 0 -6  1]]


-15.0


In [5]:
q, r = np.linalg.qr(A)
q, r

(array([[-0.4472136 ,  0.66666667,  0.59628479],
        [-0.89442719, -0.33333333, -0.2981424 ],
        [-0.        , -0.66666667,  0.74535599]]),
 array([[-2.23606798, -4.47213595,  0.        ],
        [ 0.        ,  9.        , -0.66666667],
        [ 0.        ,  0.        ,  0.74535599]]))