In [2]:
import torch
import torch.nn as nn
from res.plot_lib import set_default, show_scatterplot, plot_bases
from matplotlib.pyplot import plot, title, axis
import matplotlib.pyplot as plt
import numpy as np

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Inverse Matrices, Column Space, Rank, and Null Space

Matrix Algebra is most useful when solving *linear* systems of equations, such as:

$$
\begin{align}
2x + 4y + -2z &= 3 \\
4x + 9y + -3z &= 8 \\
-2x - 3y + 7z &= 10
\end{align}
$$

Which is simply a list of equations with unkown variables. These linear system of equations can be packaged into a single vector equation where:
 - Matrix contains coefficients $A$
 - Vector contains variables $\hat{x}$
 - Output vector (matrix-vector output) $\hat{b}$

$$
\underbrace{\begin{bmatrix} 2 & 4 & -2 \\ 4 & 9 & -3 \\ -2 & -3 & 7 \end{bmatrix}}_{\mathbf{A}}
\underbrace{\begin{bmatrix} x \\ y \\ z \end{bmatrix}}_{\mathbf{x}} =
\underbrace{\begin{bmatrix} 3 \\ 8 \\ 10 \end{bmatrix}}_{\mathbf{b}}
$$

Solving the system is saying "we're looking for a vector $\vec{x}$, which after applying the transformation $A$, lands on the vector $\vec{b}$" 

With the inverse matrix, $A^-1$, you will find the vector $\vec{x}$, that when applied to $A$, gets you to $\vec{b}$ 

Note that $\mathbf{A}^{-1}\mathbf{A} = \mathbf{I}$, where $\mathbf{I}$ is the **identity matrix**:

_Important_: When the det(A) = 0, you cannot find the inverse (you cannot find the inverse a line or plane)

$$
\mathbf{I}_{n \times n} =
\begin{bmatrix} 
1 & 0 & ... & 0 \\
0 & 1 & ... & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & ... &1 \\
\end{bmatrix}
$$

Such that

$$
\begin{align}
\mathbf{A} \mathbf{x} &= \mathbf{b} \\
\mathbf{A^{-1}}\mathbf{A}\mathbf{x} &= \mathbf{A^{-1}}\mathbf{b} \\
\mathbf{x} &= \mathbf{A^{-1}}\mathbf{b}
\end{align}
$$

### Identity Matrix

The identity matrix $I_n$ is a special matrix of shape ($n \times n$) that is filled with $0$ except the diagonal that is filled with 1.
 - An identity matrix times some vector gives you that same vector as output

In [4]:
# Identity matrix multiplied with a vector results in the same vector
x = np.array([[2], [3], [6]])
x

array([[2],
       [3],
       [6]])

In [5]:
# Identity matrix
I = np.eye(x.shape[0])
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Identity * x = x
I.dot(x)

array([[2.],
       [3.],
       [6.]])

### Inverse Matrix

The inverse matrix is analogues to the reciprocal, or multiplicative inverse, of a nonzero number. Recall that the multiplicative inverse of a number such as 5 is 1/5 or $5^{-1}$
 - $5^{-1} * 5 = 1$ and $5 * 5^{-1} = 1$

Now, generalizing this to square matrices, instead of multiyplying the 1 as before, multiply the matrix by the identity matrix $I$

The inverse matrix is the matrix that results in the identity matrix when it is multiplied by $A$
 - That is, if you multiply the inverse matrix $A^{-1}$ by the original matrix $A$, the result will be the identity matrix $I$

This means that if we apply a linear transformation to the space with $A$, it is possible to go back with $A^{-1}$. It provides a way to **cancel the transformation**
 - $A^{-1}A$ = $I$

_Critical_ - The inverse of matrices can be very useful, for instance, to solve a set of linear equations

_Rules_:

A full generalization is possible only if the matrices involved are square. An $n$ x $n$ matrix $A$ is said to be invertible if there is an $n$ x $n$ matrix $C$ such that:

$CA = I$ and $AC = I$

where $C$ = $A^{-1}$

A matrix that is not invertible is sometimes called an singular matrix, and an invertible matrix is called an nonsingluar matrix

_Quick trick_: If the determinant of the matrix = 0, then the matrix is not invertible

In [3]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [8]:
# Compute the inverse
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [9]:
A_bis = A_inv.dot(A)
A_bis

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

### Column Space and Rank

#### Rank

When the output of a transformation is (det.) is:
 - a line, then the transformation's rank = 1
 - a plane, then the transformation's rank = 2

You can think of the rank as the # of dimensions in the output resulting from a transformation:
 - A 3d transformation's det. != 0, then rank = 3
 - A 2d transformation's det. != 0, then rank = 2
 
**Full Rank** - All rows and columns are linearly independent


#### Column Space

The set of all possible outputs for a matrix is called the column space of that matrix
 - Column space = Where $\hat{i}, \hat{j}$ lands

Null space "kernel" is a set of space where all vectors "land"
 - If vectors land on 0, then this is the **null space**
     - Null space contains all possible solutions to the equation


### Solving a System of Linear Equations

If $A$ is invertible, then matrix-equation $AX = B$ is solvable for all matrix $B$

We multiply both sides times $A^{-1}$ obtaining:

$X = A^{-1}B$

since $A^{-1}AX = I_nX = X$

$$
\underbrace{\begin{bmatrix} 2 & 4 & -2 \\ 4 & 9 & -3 \\ -2 & -3 & 7 \end{bmatrix}}_{\mathbf{A}}
\underbrace{\begin{bmatrix} x \\ y \\ z \end{bmatrix}}_{\mathbf{x}} =
\underbrace{\begin{bmatrix} 3 \\ 8 \\ 10 \end{bmatrix}}_{\mathbf{b}}
$$

In [3]:
# By "hand" first - kind of
A = np.array([[2, 4, -2],
              [4, 9, -3],
              [-2, -3, 7]])

b = np.array([3, 8, 10])

# Find the inverse of A
invA = np.linalg.inv(A)

# Take invA and multiply it by b column vector
AB = invA.dot(b)
AB.reshape(-1, 1)

array([[ 5.75],
       [-0.75],
       [ 2.75]])

In [4]:
# Using packages
x = np.linalg.solve(A, b)
x.reshape(-1, 1)

array([[ 5.75],
       [-0.75],
       [ 2.75]])

In [7]:
# With PyTorch
tensorA = torch.tensor([[2, 4, -2],
                        [4, 9, -3],
                        [-2, -3, 7]]) 

tensorb = torch.tensor([3, 8, 10])

#invA = torch.linalg.inv(tensorA)
#x = torch.linalg.solve(tensorA, tensorb)

### Gaussian Elimination - "by hand"

In [11]:
from scipy.linalg import lu

# Step 1.) Get matrix into row echelon form
augmented_matrix = np.array([[2, 4, -2, 3],
                             [4, 9, -3, 8],
                             [-2, -3, 7, 10]])

# Decomposition of augmented matrix into row echelon form
p, l, u = lu(augmented_matrix)
print(u, '\n')

# Step 2.) 

[[ 4.          9.         -3.          8.        ]
 [ 0.          1.5         5.5        14.        ]
 [ 0.          0.          1.33333333  3.66666667]] 



## Matrix Operations and Types of Matrices

_Hilbert Matrices_:

Let $n$ be a positive integer and the n-th Hilbert matrix $H = (h_{i, j})$ is a square one with:

$h_{ij = \frac{1}{1 + j - 1}}$ for all $1 \leq i, j \leq n$


Commutativity does not hold in general. . . 