In [1]:
import numpy as np
from scipy.linalg import svd
from scipy import linalg


## Singular Value Decomposition (SVD)

$A = UDV^T$

where:

$A$ = m x n (the real matrix we wish to decompose)

$U$ = m x m

$V$ = n x n

The diagnoals in the $U$ are known as the singular values of the original matrix $A$. The columns in the $U$ are called the left-singular vectors of $A$, and the columns of $V$ are called the right-singular vectors of $A$

Matrices $U$ and $V$ are both defined to be orthogonal matrices

We can interpret the singular value decomposition of $A$ in terms of the eigendecomposition of functions of $A$:
 - The left-singular vectors of $A$ are the eigenvectors of $AA^T$ which is the $U$ matrix
 - The right-singluar vectors of $A$ are the eigenvectors of $A^TA$ which is the $V$ matrix
 - The non-zero singular values of $A$ are the square roots of the eigenvalues of $A^TA$ and the same is true for $AA^T$ which is the $S$ matrix

In [2]:
A = np.array([[2, 4], [1, 3], [0, 0], [0, 0]])
A

array([[2, 4],
       [1, 3],
       [0, 0],
       [0, 0]])

In order to determine the associated $U$ matrix, we must first find the eigenvectors of the $A$ matrix multiplied by the transpose of the matrix $A$
 - Remember: From my eigenvector notebook, the eigenvector is the vector that is scaled, but is not moved off of its original span (change only in scale; not direction)

In [3]:
AAT = np.dot(A, A.T)
AAT ## We now have a square matrix

array([[20, 14,  0,  0],
       [14, 10,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [4]:
# Compute left singular vectors of A which are the eigenvectors of AAT - this is the U matrix
eigenvalues, eigenvectors = linalg.eig(AAT)[0], linalg.eig(AAT)[1]
eigenvalues

array([29.86606875+0.j,  0.13393125+0.j,  0.        +0.j,  0.        +0.j])

In [40]:
U = eigenvectors
U

array([[ 0.81741556, -0.57604844,  0.        ,  0.        ],
       [ 0.57604844,  0.81741556,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In order to determine the associated $V$ matrix we must compute the following:

$V = A^TA$

$V$ = d x d

The columns of $V$ are called the right-singular vectors of $A$


In [5]:
# Compute right singular vectors of A which are the eigenvectors of ATA - this is the V matrix
ATA = np.dot(A.T, A)
V = linalg.eig(ATA)[1]
V

array([[-0.9145143 , -0.40455358],
       [ 0.40455358, -0.9145143 ]])

$S$ is the square root of either $AA^T$ or $A^TA$

In [6]:
# Take square root of AAT matrix - this is the S matrix
S = np.sqrt(eigenvalues)
S

array([5.4649857 +0.j, 0.36596619+0.j, 0.        +0.j, 0.        +0.j])

## Using scipy

In [69]:
svd(A)

(array([[-0.81741556, -0.57604844,  0.        ,  0.        ],
        [-0.57604844,  0.81741556,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]))